name: Trueconomy
version: ${project.version}
main: com.maxphillipsdev.trueconomy.Trueconomy
depends: [Vault]
api-version: 1.13
description: An economy plugin for Spigot with a focus on economic theory.
commands:
  econ:
    description: Issues main command
